version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: order-management-db
    environment:
      POSTGRES_DB: order_management
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-management-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-management-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_management
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - order-management-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  order-management-network:
    driver: bridge
